name: audio_recorder
description: A Flutter plugin to record audio.
version: 1.0.2
homepage: https://github.com/ZaraclaJ/audio_recorder

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  path: ^1.5.1
  flutter:
    sdk: flutter
  file: ^6.1.0

flutter:
  plugin:
    androidPackage: com.jordanalcaraz.audiorecorder.audiorecorder
    pluginClass: AudioRecorderPlugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
  path_provider: 2.0.1